<a href="https://colab.research.google.com/github/renatachavezm22/Extraccion-de-datos-ACT/blob/main/Extraccio%CC%81n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
#Cargar archivo csv desde equipo
#from google.colab import files
#files.upload()

CARGA DE ARCHIVO .CSV

In [42]:
#Convertir en dataframe
#df= pd.read_csv("file.csv")
#df

CARGA DE ARCHIVO XLSX

In [43]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
df

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [44]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   datetime64[ns]
 2   NOMBRE_VENDEDOR            1424 non-null   object
 3   NOMBRE_CLIENTE             1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   float64
 8   COSTO_UNITARIO             1426 non-null   float64
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   float64
 10  SUBTOTAL_PARTIDA           1426 non-null   float64
 11  COSTO_TOTAL_CALCULADO      1426 non-null   float64
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   float64
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 156.1+ KB

In [45]:
#Imprimo los primeros 5 registro del dataframe
df.head()

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [46]:
#Filtro por objeto 
#Declaras la variable igualas al dataframe y ahi abres una lista y pones la columna así como el valor de la columna que quieres.
filtro1=df[df["NOMBRE_CLIENTE"] == "PÚBLICO EN GENERAL"]
filtro1

#AQUI LO QUE BUSCAMOS ES SABER CUAL ES EL NÚMERO DE CLIENTES DECLARADOS COMO PÚBLICO GENERAL Y SABER CUAL ES EL VENDEDOR CON MÁS ALCANCE EN ESTA AREA.

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
57,F37134,2022-01-17,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,4,RB00010,BOB 8020 CAL.19 1612W 127V CER-8CANALES,605.00,44.70,44.70,2420.00,178.80,560.30,2241.20
69,F37153,2022-01-20,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00245,BAN P COMUN 100CMX21MM 900W220V T/TOR,522.00,51.38,51.38,1044.00,102.76,470.62,941.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1371,F39748,2022-12-09,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,TUE00206,"TUB INOX 5/16""Øx930mm 1000W 127V CAPUCHO",576.65,0.00,366.62,1153.30,733.23,210.03,420.07
1375,F39752,2022-12-13,AARON NUÑO CORDOVA,PÚBLICO EN GENERAL,1,TU5/16X870J127V,"TUB INOX 5/16""ØX800MM 2000W127V ""J"" TBOY",689.63,227.18,227.18,689.63,227.18,462.44,462.44
1376,F39754,2022-12-13,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,4,CS14D2017B20,"CAS INOX 1/4""ØX2"" 175W240V EXT30CM C/TJ",3416.00,222.14,222.14,6832.00,444.27,3193.86,6387.73
1392,F39780,2022-12-16,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TP0012,"TERMOPAR CERAMICO T/ K"" LONG 12"" CAL.14""",410.00,57.60,57.60,410.00,57.60,352.40,352.40
1410,F39817,2022-12-22,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,TP0016,"TERMOPAR CERAMICO T/K"" LONG 24"" CAL 8""",732.00,0.00,317.50,1464.00,635.00,414.50,829.00

In [73]:
#Filtro por filas
#filtro2= df.iloc[3:10,: ] #Filas consecutivas (Filas,Columnas; para que sea consecutivo son dos puntos pero no hay necesidad de corchete)
filtro2=df.iloc[ [8, 24, 100, 450, 750] , : ]  #Filas no consecutivas (Los dos puntos significan todos)
filtro2

# AQUI NUESTRO ENFOQUE FUE BUSCAR DE MANERA ALEATORIA 5 POSICIONES Y VER CUALES SON LOS VENDEDORES QUE MÁS SE REPITEN ASÍ COMO VER EL COMPORTAMIENTO DE LA EMPRESA

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
24,F37069,2022-01-07,AARON NUÑO CORDOVA,ADVANEX DE MEXICO,2,RP00150,REPARACION DE TERMOPAR,1500.00,0.36,0.36,3000.00,0.72,1499.64,2999.28
100,F37223,2022-01-28,LETICIA RAMIREZ HERNANDEZ,COMPONENTES ELECTRICOS Y DISPOSITIVOS ESPECIALES,1,TP0025,"TERMOPAR K 3/16Ø X 1' 1/2 EXT. 2 MT""",175.00,75.89,75.89,175.00,75.89,99.11,99.11
450,F37872,2022-04-08,LETICIA RAMIREZ HERNANDEZ,MARATHON SYSTEMS CONTROL,2,TUA00420,"TUB INOX 7/16""ØX155CM 5KW 440V ""U"" 2""NPT",3929.11,0.00,1830.01,7858.22,3660.03,2099.10,4198.19
750,F38487,2022-06-30,LETICIA RAMIREZ HERNANDEZ,TERMOFORMADOS,6,TUS00018,"TUB INOX. 5/16 Øx625mm 850W,220V U",625.70,0.00,98.64,3754.20,591.85,527.06,3162.35

In [48]:
#Filtro por columnas
filtro3=df.iloc[ : , 1:4]       #Columnas consecutivas 
#filtro3=df.iloc[ : , [1,4,6]]  #Columnas no consecutivas 
filtro3

#SE BUSCA VISUALIZAR LAS FECHAS, VENDEDORES ASÍ COMO CLIENTES QUE SE TIENEN EN 2022

      FECHA_DOC            NOMBRE_VENDEDOR                NOMBRE_CLIENTE
0    2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL
1    2022-01-05  LETICIA RAMIREZ HERNANDEZ  JUAN ANTONIO RESENDIZ UGALDE
2    2022-01-05   DIEGO ARMANDO LEON DURAN     ANA BARBARA CRUZ PALACIOS
3    2022-01-05   DIEGO ARMANDO LEON DURAN          OMAR RODRIGUEZ GOMEZ
4    2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL
...         ...                        ...                           ...
1421 2022-12-23  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ
1422 2022-12-23  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ
1423 2022-12-23  LETICIA RAMIREZ HERNANDEZ          SEVEN DAYS ALL SPORT
1424 2022-12-23  LETICIA RAMIREZ HERNANDEZ           REVUELTA MONTECARLO
1425 2022-12-23         AARON NUÑO CORDOVA                CPEG SOLUTIONS

[1426 rows x 3 columns]

In [49]:
#Filtro de filas vs columnas 
#Paso 1: Leemos el contenido del archivo
#from google.colab import files
#uploaded=files.upload()

In [50]:
df1= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx', index_col=3)
df1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
NOMBRE_CLIENTE,,,,,,,,,,,,,
PÚBLICO EN GENERAL,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
JUAN ANTONIO RESENDIZ UGALDE,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
ANA BARBARA CRUZ PALACIOS,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
OMAR RODRIGUEZ GOMEZ,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
PÚBLICO EN GENERAL,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
LUIS ENRIQUE PATIÑO PEREZ,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
LUIS ENRIQUE PATIÑO PEREZ,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
SEVEN DAYS ALL SPORT,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
REVUELTA MONTECARLO,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
CPEG SOLUTIONS,F39838,2022-12-23,AARON NUÑO CORDOVA,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [54]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
filtro4=df1.loc[["LUIS ENRIQUE PATIÑO PEREZ","ANA BARBARA CRUZ PALACIOS"], ["COSTO_TOTAL_CALCULADO"]]
filtro4

#LOC es con nombres de las columnas o nombres de los indices
#ILOC es con las posiciones de los datos

#BUSCAMOS DOS CLIENTES REELVANTES Y VER EL COSTO TOTAL QUE SE TIENE DE LA EMPRESA CON LOS PROYECTOS QUE ESTE HAN TENIDO.

                           COSTO_TOTAL_CALCULADO
NOMBRE_CLIENTE
LUIS ENRIQUE PATIÑO PEREZ                 533.70
LUIS ENRIQUE PATIÑO PEREZ                 547.28
LUIS ENRIQUE PATIÑO PEREZ                 613.88
LUIS ENRIQUE PATIÑO PEREZ                 628.12
ANA BARBARA CRUZ PALACIOS                1243.73
ANA BARBARA CRUZ PALACIOS                 116.88
ANA BARBARA CRUZ PALACIOS                 689.45
ANA BARBARA CRUZ PALACIOS                 783.24
ANA BARBARA CRUZ PALACIOS                2408.67
ANA BARBARA CRUZ PALACIOS                 520.79
ANA BARBARA CRUZ PALACIOS                 274.16
ANA BARBARA CRUZ PALACIOS                 379.50
ANA BARBARA CRUZ PALACIOS                 693.49
ANA BARBARA CRUZ PALACIOS                 757.39
ANA BARBARA CRUZ PALACIOS                2617.65
ANA BARBARA CRUZ PALACIOS                5266.17
ANA BARBARA CRUZ PALACIOS                3998.41
ANA BARBARA CRUZ PALACIOS                1434.11
ANA BARBARA CRUZ PALACIOS                1417.21
ANA BARBARA CRUZ PALACIOS                1471.68
ANA BARBARA CRUZ PALACIOS                2865.87
ANA BARBARA CRUZ PALACIOS                1182.99
ANA BARBARA CRUZ PALACIOS                1136.37
ANA BARBARA CRUZ PALACIOS                 308.87
ANA BARBARA CRUZ PALACIOS                 257.43
ANA BARBARA CRUZ PALACIOS                1160.05
ANA BARBARA CRUZ PALACIOS                1181.01

In [55]:
#Filtro por cabecera
filtro5=df.head(10)
filtro5

#DESPLEGAR LOS PRIMEROS 10 DATOS DE LA BASE DE DATOS

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [59]:
#Filtro por comparacion
filtro6=df[df["MARGEN_TOTAL_CALCULADO"] > 10000]
filtro6

#AQUI BUSCAMOS VER EL MARGEN POR ARRIBA DE 10000 PESOS QUE HA TENIDO LA EMPRESA Y VEMOS QUE SON SOLAMENTE 10 CASOS LOS CUALES SE TUVO ESTE MARGEN

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
29,F37078,2022-01-07,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.60,9163.18,993.88,29816.42
31,F37086,2022-01-10,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.60,9163.18,993.88,29816.42
40,F37102,2022-01-12,ALFREDO CANELA,DEACERO,3,TUE00321,"TUB INOX 1/2""ØX1030MMX980MM 3KW480V ""L""",12720.00,0.00,1509.14,38160.00,4527.42,11210.86,33632.58
65,F37147,2022-01-19,ALFREDO CANELA,VALEO KAPEC,8,TUA00258,"TUB INOX 7/16""Øx190mm 2000W 400V BUS/LAT",2177.50,272.65,272.65,17420.00,2181.22,1904.85,15238.78
74,F37169,2022-01-21,ALFREDO CANELA,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,30,ECQ-00972,"TUB. ENCAPSULADA 5/16Øx780mm 1500W 240V""",1475.30,275.50,275.50,44259.00,8264.95,1199.80,35994.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,F39791,2022-12-20,LETICIA RAMIREZ HERNANDEZ,PLENCO DE MEXICO,6,TUA00433,"TUB INOX 1/2""ØX1015MM 5KW 240V ""U"" ALETA",2494.80,0.00,620.47,14968.80,3722.84,1874.33,11245.96
1397,F39794,2022-12-20,AARON NUÑO CORDOVA,TE.MEX AUTOMOTIVE,26,CAS00083,CAS INOX 12.5MMØX125MM 300W 280V EXT1MT,792.11,131.45,131.45,20594.86,3417.80,660.66,17177.06
1403,F39810,2022-12-22,ALFREDO CANELA,DONGA HWASUNG MEXICO,16,CBS00109,"CBS INOX 5/8""ØX66CM 800W 480V EXT30CM",1981.88,0.00,333.62,31710.08,5337.90,1648.26,26372.18
1409,F39816,2022-12-22,ALFREDO CANELA,TOSTADAS FANNY,6,TUA00492,"TUB INOX 1/2""ØX40CM 4000W 220V ""M"" BUSH",2959.68,0.00,1186.76,17758.08,7120.54,1772.92,10637.54
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

**FILTROS BASICOS CON CONETORES LOGICOS**

In [70]:
#Filtro Y
filtro7=df[(df["PRECIO_UNITARIO"] > 750) & (df["FECHA_DOC"] == "2022-12-20")]
filtro7

#Cumplen las dos condiciones.

#AQUI BUSCAMOS QUE LA FECHA DEL 20 DE DICIEMBRE Y QUE EL PRECIO POR UNIDAD DEL ARTICULO VENDIDO HAYA SIDO POR ARRIBA DE 750 PESOS. VEMOS QUE SOLO 3 ARTICULOS FUERON VENDIDOS POR ARRIBA DE ESE PRECIO EN ESE DIA.

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1394,F39791,2022-12-20,LETICIA RAMIREZ HERNANDEZ,PLENCO DE MEXICO,6,TUA00433,"TUB INOX 1/2""ØX1015MM 5KW 240V ""U"" ALETA",2494.80,0.00,620.47,14968.80,3722.84,1874.33,11245.96
1397,F39794,2022-12-20,AARON NUÑO CORDOVA,TE.MEX AUTOMOTIVE,26,CAS00083,CAS INOX 12.5MMØX125MM 300W 280V EXT1MT,792.11,131.45,131.45,20594.86,3417.80,660.66,17177.06
1398,F39794,2022-12-20,AARON NUÑO CORDOVA,TE.MEX AUTOMOTIVE,10,CAS00084,CAS INOX 12.5MMØX165MM 300W 280V EXT.1MT,798.79,137.63,137.63,7987.90,1376.26,661.16,6611.64

In [71]:
#Filtro o
filtro8=df[(df["PRECIO_UNITARIO"] > 750) | (df["FECHA_DOC"] == "2022-12-20")]
filtro8

#AQUI HACEMOS ALGO SIMILAR A LO ANTERIOR PERO VENTAS CON PRECIO UNITARIO MAYOR A 750 Y QUE SEAN DE ESA FECHA VEMOS QUE SOM MAS DE 800 DATOS.

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
10,F37050,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BN00146,"BAN INOX 9""ØX3"" ANCH 1700W 230V T/CABLE",2020.42,421.91,421.91,4040.84,843.82,1598.51,3197.02
1420,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,PT00079,PT-100 7.5MMØX95MM EXT.48CM 3H C/MACHO,1177.07,477.16,477.16,2354.14,954.32,699.91,1399.82
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [72]:
#Filtro not
filtro9=df[~(df["PRECIO_UNITARIO"] > 750) & ~(df["FECHA_DOC"] == "2022-12-20")]
filtro9

#BUSCAMOS QUE EL PRECIO UNITARIO SEA MAYOR A 750 PERO NO ME CUENTEN LOS 3 LA FECHA ASIGNADA.

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1410,F39817,2022-12-22,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,TP0016,"TERMOPAR CERAMICO T/K"" LONG 24"" CAL 8""",732.00,0.00,317.50,1464.00,635.00,414.50,829.00
1414,F39828,2022-12-23,LETICIA RAMIREZ HERNANDEZ,JUAN GERARDO GUZMAN FLORES,3,TP00018,"TIRA INOX 38MMX6"" 150W 127V T/TIPO H",510.00,51.16,51.16,1530.00,153.49,458.84,1376.51
1416,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,3,PJ31Q1G1A400,"TER J 3/16""ØX1/2"" EXT3MT MALLA INOX Z/E",439.15,0.00,123.21,1317.45,369.62,315.94,947.83
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48

In [76]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("FILTRO1.csv")
filtro9.to_csv("FILTRO2.csv")
filtro9.to_csv("FILTRO3.csv")
filtro9.to_csv("FILTRO4.csv")
filtro9.to_csv("FILTRO5.csv")
filtro9.to_csv("FILTRO6.csv")
filtro9.to_csv("FILTRO7.csv")
filtro9.to_csv("FILTRO8.csv")
filtro9.to_csv("FILTRO9.csv")

In [77]:
#descardar archivo filtrado en csv
from google.colab import files 
  
files.download("FILTRO1.csv")
files.download("FILTRO2.csv")
files.download("FILTRO3.csv")
files.download("FILTRO4.csv")
files.download("FILTRO5.csv")
files.download("FILTRO6.csv")
files.download("FILTRO7.csv")
files.download("FILTRO8.csv")
files.download("FILTRO9.csv")